export const skills = [
  {
    title: 'Front-End & User Interface',
    items: [
      'React',
      'Redux',
      'DvaJS',
      'Next.js',
      'CSS/SASS/SCSS',
      'Styled Components',
      'JavaScript',
      'TypeScript',
      'Ant Design',
      'Bootstrap',
      'Material Design',
      'Storybook',
      'Svelte',
    ],
  },
  {
    title: 'Back-End',
    items: [
      'Node.js',
      'RESTful API',
      'Express',
      'Fastify',
      'TypeORM',
      'PostgreSQL',
      'MySQL',
      'AWS',
    ],
  },
  {
    title: 'Frameworks & Testing',
    items: [
      'Webpack',
      'Rollup.js',
      'Gatsby',
      'axios',
      'Cypress',
      'Jest(Enzyme)',
      'React Testing Library',
    ],
  },
  {
    title: 'Tools',
    items: [
      'npm',
      'git',
      'Webpack',
      'Firebase',
      'Postman',
      'ESLint',
      'Prettier',
      'Google Analytics',
      'Google Maps API',
    ],
  },
];
